vector_db_path: "./data/faiss_index"
device: "cuda:0" # ["auto", "cpu", "cuda:0"]
hf_dataset: "m-ric/huggingface_doc"
embedding_model_name: "thenlper/gte-small"
embedding_model_chunksize: 512
chat_model_name: "stabilityai/stablelm-zephyr-3b"
# Larger and smaller alternative models
# "HuggingFaceH4/mistral-7b-sft-beta"
# "HuggingFaceH4/zephyr-7b-beta"
# "EleutherAI/gpt-neo-125m"
llm:
  task: "text-generation"
  do_sample: True
  temperature: 0.2
  repetition_penalty: 1.1
  return_full_text: False
  max_new_tokens: 500
query:
  k: 5